### ISSUE TITLE
Push 0.15 to dockerhub

### ISSUE THREAD

**Issue by bavedarnow** [jayclassless/tidypy#42]
Is there any reason why the new version isn't up on docker hub? Thanks!

**Comment by jayclassless** [comment]
Turns out there was a parade of errors. The docker build started failing a while back, but I never got any failure notices, and then the Docker/GitHub integration for this project broke altogether, so it stopped trying.

At any rate, I fixed the build, and published the latest version (`0.16.0`) to Docker Hub. Thanks for pointing out the problem!
